require_relative 'base'

module Bucket
  class Vars
    class Place < Base
      LIST = [
        "airport",
        "amusement park",
        "aquarium",
        "art gallery",
        "atm",
        "bakery",
        "bank",
        "bar",
        "beauty salon",
        "bicycle store",
        "book store",
        "bowling alley",
        "bus station",
        "cafe",
        "campground",
        "car dealer",
        "car rental",
        "car repair",
        "car wash",
        "casino",
        "cemetery",
        "church",
        "city hall",
        "clothing store",
        "convenience store",
        "courthouse",
        "dentist",
        "department store",
        "doctor",
        "electronics store",
        "embassy",
        "finance",
        "fire station",
        "florist",
        "funeral home",
        "furniture store",
        "gas station",
        "supermarket",
        "gym",
        "hair dresser",
        "hardware store",
        "health",
        "hindu temple",
        "home goods store",
        "hospital",
        "insurance agency",
        "jewelry store",
        "laundry",
        "lawyer",
        "library",
        "liquor store",
        "locksmith",
        "lodging",
        "mosque",
        "movie theater",
        "museum",
        "night club",
        "park",
        "parking",
        "pet store",
        "pharmacy",
        "physiotherapist",
        "police",
        "post office",
        "real estate agency",
        "restaurant",
        "roofing contractor",
        "rv park",
        "school",
        "shoe store",
        "shopping mall",
        "spa",
        "stadium",
        "storage",
        "store",
        "subway station",
        "synagogue",
        "taxi stand",
        "train station",
        "travel agency",
        "university",
        "vet",
        "zoo"
      ]
    end
  end
end
