require_relative 'base'

module Bucket
  class Vars
    class Vehicle < Base
      LIST = [
        "aircraft",
        "aircraft carrier",
        "airplane",
        "ambulance",
        "amphibious vehicle",
        "balloon",
        "bathyscaphe",
        "barge",
        "barrow",
        "battleship",
        "bicycle",
        "bike",
        "biplane",
        "blimp",
        "boat",
        "bobsled",
        "broomstick",
        "buggy",
        "bulldozer",
        "bullet train",
        "bus",
        "cab",
        "cabin cruiser",
        "cable car",
        "caboose",
        "camper van",
        "canoe",
        "car",
        "caravan",
        "caravel",
        "cargo ship",
        "carriage",
        "catamaran",
        "chairlift",
        "chariot",
        "chopper",
        "coach",
        "combine",
        "container ship",
        "convertible",
        "conveyor belt",
        "crane",
        "crop duster",
        "cruise ship",
        "delivery van",
        "destroyer",
        "dinghy",
        "dirt bike",
        "diving bell",
        "dog cart",
        "dogsled",
        "donkey cart",
        "dray",
        "driver",
        "dugout canoe",
        "dump truck",
        "earth mover",
        "eighteen-wheeler",
        "ekranoplan",
        "elevator",
        "escalator",
        "ferry",
        "fireboat",
        "fire engine",
        "fishing boat",
        "flatbed truck",
        "forklift",
        "four-by-four",
        "freighter",
        "freight train",
        "frigate",
        "galleon",
        "garbage truck",
        "glider",
        "go-cart",
        "golf cart",
        "gondola",
        "handcar",
        "hang glider",
        "hansom cab",
        "hardtop",
        "hatchback",
        "hay wagon",
        "hearse",
        "helicopter",
        "hovercraft",
        "hot-air balloon",
        "hot rod",
        "houseboat",
        "humvee",
        "hydrofoil",
        "hydroplane",
        "ice boat",
        "ice breaker",
        "jet boat",
        "jetliner",
        "jet pack",
        "jet ski",
        "jumbo jet",
        "kayak",
        "landing craft",
        "life raft",
        "light rail",
        "limousine",
        "litter",
        "locomotive",
        "lorry",
        "low-rider",
        "magic carpet",
        "maglev",
        "monorail",
        "moped",
        "motorboat",
        "motorcycle",
        "motor home",
        "mountain bike",
        "ocean liner",
        "oil tanker",
        "outrigger canoe",
        "oxcart",
        "paddlewheeler",
        "parachute",
        "pedal boat",
        "pickup truck",
        "plane",
        "police car",
        "power boat",
        "prairie schooner",
        "punt",
        "push cart",
        "raft",
        "ragtop",
        "rickshaw",
        "roadster",
        "rocket",
        "rowboat",
        "sailboat",
        "satellite",
        "school bus",
        "scooter",
        "seaplane",
        "Segway",
        "ski lift",
        "sled",
        "sleigh",
        "snow cat",
        "snowmobile",
        "snowplow",
        "spaceship",
        "space shuttle",
        "speedboat",
        "sports car",
        "steamboat",
        "stretch hummer",
        "submarine",
        "tank",
        "taxi",
        "toboggan",
        "tow truck",
        "trail bike",
        "train",
        "tram",
        "tricycle",
        "trolley",
        "truck",
        "tugboat",
        "ultralight craft",
        "unicycle",
        "van",
        "vespa",
        "wheelchair",
        "yacht",
        "Zamboni",
        "zeppelin"
      ]
    end
  end
end

